// [!output SAFE_IDL_NAME].idl : источник библиотеки типов для [!output PROJECT_NAME].exe

// Этот файл будет обработан компилятором MIDL для создания
// библиотеки типов ([!output SAFE_IDL_NAME].tlb).

[ uuid([!output LIBID_REGISTRY_FORMAT]), version(1.0) ]
library [!output LIB_NAME]
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	//  Первичный интерфейс диспетчеризации для [!output DOC_CLASS]
	
	[ uuid([!output DISPIID_REGISTRY_FORMAT]) ]
	dispinterface I[!output SAFE_PROJECT_IDENTIFIER_NAME]
	{
		properties:
			
		methods:
	};

	//  Информация о классе для [!output DOC_CLASS]
	
	[ uuid([!output APP_CLSID_REGISTRY_FORMAT]) ]
[!if APP_TYPE_DLG]
	coclass [!output SAFE_PROJECT_IDENTIFIER_NAME]
[!else]
	coclass [!output DOC_CLASS]
[!endif]
	{
		[default] dispinterface I[!output SAFE_PROJECT_IDENTIFIER_NAME];
	};
};
